//
// Created by ASUS on 2023/10/4.
//

#ifndef FETCHTEXTURE_STITCHTEXTUREWIDGETACTION_H
#define FETCHTEXTURE_STITCHTEXTUREWIDGETACTION_H


class StitchTextureWidgetAction {

};


#endif //FETCHTEXTURE_STITCHTEXTUREWIDGETACTION_H
