//
// Created by ASUS on 2023/10/4.
//

#ifndef FETCHTEXTURE_UNITTEXTUREWIDGETACTION_H
#define FETCHTEXTURE_UNITTEXTUREWIDGETACTION_H


class UnitTextureWidgetAction {

};


#endif //FETCHTEXTURE_UNITTEXTUREWIDGETACTION_H
