//
// Created by ASUS on 2023/10/15.
//

#ifndef IMAGEOPERATION_FREQUENCYDOMAINFILTERING_H
#define IMAGEOPERATION_FREQUENCYDOMAINFILTERING_H


class FrequencyDomainFiltering {

};


#endif //IMAGEOPERATION_FREQUENCYDOMAINFILTERING_H
