//
// Created by ASUS on 2023/10/15.
//

#ifndef IMAGEOPERATION_WAVELETANDMULTIRESOLUTIONPROCESSING_H
#define IMAGEOPERATION_WAVELETANDMULTIRESOLUTIONPROCESSING_H


class WaveletAndMultiResolutionProcessing {

};


#endif //IMAGEOPERATION_WAVELETANDMULTIRESOLUTIONPROCESSING_H
